import AuthProvider from "@/components/AuthProvider";
import "./globals.css";
import { Inter } from "next/font/google";
import ReduxProvider from "@/components/ReduxProvider";
import { ReactQueryProvider } from "@/components/ReactQueryProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="dark">
        <AuthProvider>
          <ReduxProvider>
            <ReactQueryProvider>
              <main>{children}</main>
            </ReactQueryProvider>
          </ReduxProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
